# gitzone ci_default
image: hosttoday/ht-docker-dbase:npmci

cache:
  paths:
  - .npmci_cache/
  key: "$CI_BUILD_STAGE"

stages:
- metadata

pages:
  image: hosttoday/ht-docker-dbase:npmci
  services:
   - docker:18-dind
  stage: metadata
  script:
    - npmci npm install
    - npmci command npm run build
  tags:
    - docker
    - priv
  only:
    - tags
  artifacts:
    expire_in: 1 week
    paths:
    - public
  allow_failure: true
